export default {
  light: {
    text: '#000',
    background: '#f2f2f2',
    tabIconDefault: '#484C52',
    tabIconSelected: '#539DF3',
    seperator: '#484C52',
    image: require("../assets/images/logo-light.png"),
    buttonColor: "#FFFFFF",
    subTitle: "#1970B4",
    barStyle: 'dark-content',
    clickableText: "darkblue",
    borderColor: "black",
  },
  dark: {
    text: '#fff',
    background: '#404040',
    tabIconDefault: '#BFC9D9',
    tabIconSelected: '#539DF3',
    seperator: '#BFC9D9',
    image: require("../assets/images/logo-dark.png"),
    buttonColor: "#5E5E5E",
    subTitle: "#1970B4",
    barStyle: 'light-content',
    clickableText: "lightblue",
    borderColor: "lightgrey",
  },
};
