name: capstone-project-2024-s1-team-7-noot-noot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean spring-boot:run
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: Backend_API - NootNoot
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
#      - name: Download Artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: Backend_API - NootNoot
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: SightSaver-API
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
#          packa